### ISSUE TITLE
Exception being thrown in case of valid input

### ISSUE THREAD

**Issue by georgthegreat** [torakiki/pdfsam#207]
Merge module throws upon attempting to merge singe item with ranges like `1-7,6,8-`
```
ERROR  [19:56:25]: Task execution failed due to invalid parameters: Invalid page ranges, found an intersection between 1-7 and 6
... Personal stuff omitted...
nvalid page ranges, found an intersection between 1-7 and 6"
at org.sejda.core.service.DefaultTaskExecutionService.validate(DefaultTaskExecutionService.java:109)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:66)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```
It's still possible to duplicate the entry and merge the result as needed. 
I think sedja should stop throwing in that case

**Comment by torakiki** [comment]
It currently expects to have no intersections between page ranges but sure, it can be improved to be smarter handling this kind of ranges.
