### ISSUE TITLE
map failed

### ISSUE THREAD

**Issue by olivierpalmer** [torakiki/pdfsam#210]
Hi,

First try of PDFsam, got this error :

```
INFO   [16:50:06]: Started in 6 seconds
INFO   [16:50:18]: ExpoJJ-PanneauxPVC-print-copie.pdf loaded
INFO   [16:50:28]: Starting task (org.sejda.impl.sambox.ExtractPagesTask@e577c5) execution.
ERROR  [16:50:28]: Task (org.sejda.impl.sambox.ExtractPagesTask@e577c5) execution failed.
org.sejda.model.exception.TaskIOException: An error occurred opening the source: C:\Users\Oli\Documents\expo\ExpoJJ-PanneauxPVC-print-copie.pdf.
at org.sejda.impl.sambox.component.DefaultPdfSourceOpener.open(DefaultPdfSourceOpener.java:67)
at org.sejda.impl.sambox.component.DefaultPdfSourceOpener.open(DefaultPdfSourceOpener.java:39)
at org.sejda.model.input.PdfFileSource.open(PdfFileSource.java:51)
at org.sejda.impl.sambox.ExtractPagesTask.execute(ExtractPagesTask.java:81)
at org.sejda.impl.sambox.ExtractPagesTask.execute(ExtractPagesTask.java:54)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:144)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Map failed
at sun.nio.ch.FileChannelImpl.map(Unknown Source)
at org.sejda.io.MemoryMappedSeekableSource.<init>(MemoryMappedSeekableSource.java:64)
at org.sejda.io.SeekableSources.seekableSourceFrom(SeekableSources.java:74)
at org.sejda.impl.sambox.component.DefaultPdfSourceOpener.open(DefaultPdfSourceOpener.java:61)
... 11 common frames omitted
Caused by: java.lang.OutOfMemoryError: Map failed
at sun.nio.ch.FileChannelImpl.map0(Native Method)
... 15 common frames omitted
```

Would you have a clue ?

cheers
Olivier

**Comment by torakiki** [comment]
Hi Oliver, could you give us some more details? like PDFsam version, Java version, OS version and RAM on your machine?

**Comment by olivierpalmer** [comment]
Hello torakiki,
sure, sorry,

pdfsam v3.2.5 
java  1.8.0_121-b13
os win7 sp1 32b
4Go Ram

The file i'm trying to extract from is 1,2go, quite big

looking forward to hearing from you.

**Comment by torakiki** [comment]
This is usually fixed by switching from a 32bits Java to a 64bits one, but we can't because you are on a 32bits system. We wrote a fix to avoid using memory mapped io on 32bits systems, it's committed but not released with PDFsam yet so here is what we could try... you have a file called `pdfsam.l4j.ini` in your PDFsam directory, open it with a text editor and change the line `-Xmx512m` to `-Xmx2g` then add the following new line `-Dorg.sejda.io.mapped.disabled=true`, save and try running PDFsam again using the Windows start menu entry.

**Comment by olivierpalmer** [comment]
Hi, thanks for the help
pdfsam shortly appears in the task manager but closes right after. 
I notice the tip about going on a 64bits system, I'll try that and get back to you.

**Comment by torakiki** [comment]
We can try the way around..change `-Xmx512m` to `-Xmx1024m` and see if works, if not move up to 1500..

**Comment by olivierpalmer** [comment]
It worked, well done !
