### ISSUE TITLE
Split creating temp files instead of splitting entire document

### ISSUE THREAD

**Issue by buzzed1** [torakiki/pdfsam#279]
Some files are split but others are only temporary files and the split fails with errors. This occurs in version 3.3.5.

INFO   [20:15:48]: Starting task (org.sejda.impl.sambox.SplitByPageNumbersTask@23ed4cd1) execution.
ERROR  [20:16:01]: Task (org.sejda.impl.sambox.SplitByPageNumbersTask@23ed4cd1) execution failed.
org.sejda.model.exception.TaskOutputVisitException: Exception dispatching the file or directory task output.
at org.sejda.model.output.FileOrDirectoryTaskOutput.accept(FileOrDirectoryTaskOutput.java:50)
at org.sejda.impl.sambox.component.split.AbstractPdfSplitter.split(AbstractPdfSplitter.java:106)
at org.sejda.impl.sambox.SplitByPageNumbersTask.execute(SplitByPageNumbersTask.java:76)
at org.sejda.impl.sambox.SplitByPageNumbersTask.execute(SplitByPageNumbersTask.java:45)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:148)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: Source 'S:\Personal Folders\pdfsam\.sejdaTmp4882695799012177305.tmp' does not exist
at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2980)
at org.sejda.core.support.io.OutputWriterHelper.doMoveFile(OutputWriterHelper.java:164)
at org.sejda.core.support.io.OutputWriterHelper.moveFile(OutputWriterHelper.java:157)
at org.sejda.core.support.io.OutputWriterHelper.moveToDirectory(OutputWriterHelper.java:115)
at org.sejda.core.support.io.DefaultMultipleOutputWriter.dispatch(DefaultMultipleOutputWriter.java:68)
at org.sejda.model.output.FileOrDirectoryTaskOutput.accept(FileOrDirectoryTaskOutput.java:48)
... 10 common frames omitted

**Comment by torakiki** [comment]
Could you try the new version an let me know if the issue is still there?
