### ISSUE TITLE
PDFsam Basic does not export / "run"

### ISSUE THREAD

**Issue by hirntot** [torakiki/pdfsam#287]
Ubuntu Mate 18.04, brand new installation. PDFsam on the same machine under Xubuntu 16.04 worked fine for me.

After pressing the "Run" button there shows up "Requested", right next to it, as if it was working. after waiting a while and wondering around what it could be I found the (geniously simple) log list which is attached. No Idea what could be causing that problem and google didn't really help me.

thanks and Cheers

> INFO   [10:14:33]: Starting PDFsam
INFO   [10:14:38]: Configuring Sejda 3.2.38
INFO   [10:14:41]: Gestarted in 7 seconds
INFO   [10:14:49]: Scannen0001.pdf loaded
INFO   [10:14:49]: Scannen0002.pdf loaded
INFO   [10:14:56]: Starting task (org.sejda.impl.sambox.MergeTask@30e412b2) execution.
WARN   [10:14:58]: New fonts found, font cache will be re-built
WARN   [10:14:58]: Building on-disk font cache, this may take a while
WARN   [10:14:58]: Missing 'name' entry for PostScript name in font /home/eden/.fonts/cambria.ttf
ERROR  [10:15:03]: Unexpected error
java.lang.NoClassDefFoundError: Could not initialize class org.sejda.sambox.pdmodel.font.PDType1Font
at org.sejda.impl.sambox.util.FontUtils.<clinit>(FontUtils.java:74)
at org.sejda.impl.sambox.component.PDDocumentHandler.close(PDDocumentHandler.java:231)
at org.sejda.common.ComponentsUtility.nullSafeClose(ComponentsUtility.java:63)
at org.sejda.common.ComponentsUtility.nullSafeCloseQuietly(ComponentsUtility.java:49)
at org.sejda.impl.sambox.MergeTask.closeResources(MergeTask.java:232)
at org.sejda.impl.sambox.MergeTask.after(MergeTask.java:237)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:151)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`

**Comment by Khayet** [comment]
I've got a similar error when trying to merge files. I'm using Ubuntu 18.04.

`INFO   [23:58:34]: Starting task (org.sejda.impl.sambox.MergeTask@486abf1) execution.
WARN   [23:58:35]: New fonts found, font cache will be re-built
WARN   [23:58:35]: Building on-disk font cache, this may take a while
ERROR  [23:58:35]: Unexpected error
java.lang.NoClassDefFoundError: Could not initialize class org.sejda.sambox.pdmodel.font.PDType1Font
at org.sejda.impl.sambox.util.FontUtils.<clinit>(FontUtils.java:74)
at org.sejda.impl.sambox.component.PDDocumentHandler.close(PDDocumentHandler.java:231)
at org.sejda.common.ComponentsUtility.nullSafeClose(ComponentsUtility.java:63)
at org.sejda.common.ComponentsUtility.nullSafeCloseQuietly(ComponentsUtility.java:49)
at org.sejda.impl.sambox.MergeTask.closeResources(MergeTask.java:232)
at org.sejda.impl.sambox.MergeTask.after(MergeTask.java:237)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:151)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
`

**Comment by torakiki** [comment]
Are you using the zip or deb package we provide here https://pdfsam.org/download-pdfsam-basic/ or the one in the Ubuntu repo?

**Comment by hirntot** [comment]
I guess I just installed the Ubuntu repo one. After uninstalling that one and installing the official .deb from the website, there was no issue anymore. well, problem solved for me! thanks
