### ISSUE TITLE
Merge issue: Could not initialize class org.sejda.sambox.pdmodel.font.PDType1Font

### ISSUE THREAD

**Issue by yulajad** [torakiki/pdfsam#297]
PDF Split and Merge Basic Edition
3.3.5
Java(TM) SE Runtime Environment 1.8.0_72-b15
Maximaler Speicher 228 MB
System:    Host: XXX Kernel: 4.15.0-29-generic x86_64 bits: 64
           Desktop: Cinnamon 3.8.8  Distro: Linux Mint 19 Tara

INFO   [10:13:45]: Starting PDFsam
INFO   [10:13:46]: Configuring Sejda 3.2.38
INFO   [10:13:47]: Gestarted in 2 seconds
INFO   [10:14:25]: 180705_alsterarbeit_optiplex7060.pdf loaded
INFO   [10:14:31]: Dell_eQuote-Nr._1015115392604__-Linux-generated_files.pdf loaded
INFO   [10:14:36]: Starting task (org.sejda.impl.sambox.MergeTask@583473ce) execution.
WARN   [10:14:37]: New fonts found, font cache will be re-built
WARN   [10:14:37]: Building on-disk font cache, this may take a while
ERROR  [10:14:39]: Unexpected error
java.lang.NoClassDefFoundError: Could not initialize class org.sejda.sambox.pdmodel.font.PDType1Font
at org.sejda.impl.sambox.util.FontUtils.<clinit>(FontUtils.java:74)
at org.sejda.impl.sambox.component.PDDocumentHandler.close(PDDocumentHandler.java:231)
at org.sejda.common.ComponentsUtility.nullSafeClose(ComponentsUtility.java:63)
at org.sejda.common.ComponentsUtility.nullSafeCloseQuietly(ComponentsUtility.java:49)
at org.sejda.impl.sambox.MergeTask.closeResources(MergeTask.java:232)
at org.sejda.impl.sambox.MergeTask.after(MergeTask.java:237)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:151)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by torakiki** [comment]
The related issue is here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899183
It's fixed in Debian but my understanding is that Debian based distros have to get the latest version of the lib, so the issue will be there until they do.
As a workaround you can uninstal the package and install our .deb from https://github.com/torakiki/pdfsam/releases
