### ISSUE TITLE
Memorry error

### ISSUE THREAD

**Issue by tiotrom** [torakiki/pdfsam#307]
When i try to merge 750 pdf files (each containing one page):

```
INFO   [17:31:17]: 597_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 598_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 599_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 600_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 601_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 602_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 603_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 604_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 605_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 606_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 607_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 608_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 609_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 610_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 611_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 612_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 613_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 614_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 615_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 616_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 617_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 618_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 619_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 620_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 621_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 622_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 623_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 624_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 625_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 626_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 627_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 628_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 629_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 630_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 631_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 632_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 633_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 634_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 635_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 636_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 637_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 638_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 639_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 640_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 641_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 642_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 643_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 644_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 645_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 646_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 647_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 648_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 649_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 650_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 651_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 652_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 653_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 654_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 655_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 656_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 657_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 658_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 659_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 660_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 661_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 662_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 663_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 664_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 665_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 666_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 667_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 668_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 669_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 670_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 671_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 672_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 673_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 674_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 675_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 676_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 677_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 678_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 679_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 680_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 681_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 682_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 683_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 684_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 685_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 686_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 687_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 688_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 689_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 690_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 691_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 692_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 693_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 694_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 695_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 696_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 697_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 698_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 699_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 700_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 701_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 702_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 703_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 704_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 705_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 706_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 707_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 708_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 709_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 710_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 711_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 712_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 713_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 714_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 715_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 716_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 717_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 718_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 719_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 720_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 721_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 722_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 723_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 724_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 725_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 726_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 727_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 728_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 729_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 730_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 731_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 732_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 733_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 734_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 735_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 736_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 737_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 738_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 739_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 740_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 741_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 742_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 743_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:17]: 744_PDFsam_The Origin of Most Problems DONE Unoptimized.pdf loaded
INFO   [17:31:34]: Starting task (org.sejda.impl.sambox.MergeTask@23b4e11c) execution.
ERROR  [17:36:44]: Unexpected error
java.lang.OutOfMemoryError: Java heap space
at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
at java.lang.StringCoding.encode(StringCoding.java:344)
at java.lang.String.getBytes(String.java:918)
at java.io.UnixFileSystem.getLastModifiedTime(Native Method)
at java.io.File.lastModified(File.java:943)
at java.util.prefs.FileSystemPreferences$10.run(FileSystemPreferences.java:737)
at java.util.prefs.FileSystemPreferences$10.run(FileSystemPreferences.java:733)
at java.security.AccessController.doPrivileged(Native Method)
at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:732)
at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:824)
at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:464)
at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
at java.util.prefs.FileSystemPreferences$3.run(FileSystemPreferences.java:432)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
ERROR  [17:36:44]: Unexpected error
java.lang.OutOfMemoryError: Java heap space
at java.util.regex.Pattern.group0(Pattern.java:2946)
at java.util.regex.Pattern.sequence(Pattern.java:2053)
at java.util.regex.Pattern.expr(Pattern.java:1998)
at java.util.regex.Pattern.compile(Pattern.java:1698)
at java.util.regex.Pattern.<init>(Pattern.java:1351)
at java.util.regex.Pattern.compile(Pattern.java:1028)
at java.util.regex.Pattern.matches(Pattern.java:1133)
at java.lang.String.matches(String.java:2121)
at org.sejda.sambox.cos.COSNumber.get(COSNumber.java:62)
at org.sejda.sambox.input.COSParser.nextNumberOrIndirectReference(COSParser.java:154)
at org.sejda.sambox.input.COSParser.nextParsedToken(COSParser.java:96)
at org.sejda.sambox.input.BaseCOSParser.nextDictionary(BaseCOSParser.java:93)
at org.sejda.sambox.input.COSParser.nextParsedToken(COSParser.java:67)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.parseObjectStream(LazyIndirectObjectsProvider.java:285)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.parseCompressedEntry(LazyIndirectObjectsProvider.java:247)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.doParse(LazyIndirectObjectsProvider.java:178)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.parseObject(LazyIndirectObjectsProvider.java:133)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.get(LazyIndirectObjectsProvider.java:75)
at org.sejda.sambox.input.ExistingIndirectCOSObject.getCOSObject(ExistingIndirectCOSObject.java:53)
at org.sejda.sambox.output.PDFWriteContext.createNewReference(PDFWriteContext.java:132)
at org.sejda.sambox.output.PDFWriteContext.createIndirectReferenceFor(PDFWriteContext.java:93)
at org.sejda.sambox.output.PDFWriteContext.getOrCreateIndirectReferenceFor(PDFWriteContext.java:166)
at org.sejda.sambox.output.PDFBodyWriter.createIndirectReferenceIfNeededFor(PDFBodyWriter.java:199)
at org.sejda.sambox.output.PDFBodyWriter.onPotentialIndirectObject(PDFBodyWriter.java:192)
at org.sejda.sambox.output.PDFBodyWriter.visit(PDFBodyWriter.java:153)
at org.sejda.sambox.cos.COSDictionary.accept(COSDictionary.java:1214)
at org.sejda.sambox.input.ExistingIndirectCOSObject.accept(ExistingIndirectCOSObject.java:68)
at org.sejda.sambox.output.PDFBodyWriter.startWriting(PDFBodyWriter.java:121)
at org.sejda.sambox.output.PDFBodyWriter.visit(PDFBodyWriter.java:108)
at org.sejda.sambox.cos.COSDocument.accept(COSDocument.java:141)
at org.sejda.sambox.output.PDFBodyWriter.write(PDFBodyWriter.java:95)
at org.sejda.sambox.output.PDDocumentWriter.writeBody(PDDocumentWriter.java:96)

```

**Comment by tiotrom** [comment]
I found this https://pdfsam.org/map-failed-and-outofmemoryerror/ and it may be a solution but I can't find pdfsam.l4j.ini anywhere in Linux

**Comment by tiotrom** [comment]
ok finally I fixed it. In Linux you can find the file in /usr/share/java/pdfsam/bin/pdfsam.sh - works now. Cheers!
