### ISSUE TITLE
[Ubuntu 18.04] Merge PDF error

### ISSUE THREAD

**Issue by m-paniez9292** [torakiki/pdfsam#313]
Hi,
First, I just discover your new version and great works.

I use pdfsam basic on Ubuntu 18.04 (install with Ubuntu package) :
```
PDF Split and Merge Basic Edition
3.3.5
Java(TM) SE Runtime Environment 1.8.0_191-b12
Mémoire maxi. 228 MB
```

I would like to merge pdf files and I have an error :
```
java.lang.NoClassDefFoundError: Could not initialize class org.sejda.sambox.pdmodel.font.PDType1Font
at org.sejda.impl.sambox.util.FontUtils.<clinit>(FontUtils.java:74)
at org.sejda.impl.sambox.component.PDDocumentHandler.close(PDDocumentHandler.java:231)
at org.sejda.common.ComponentsUtility.nullSafeClose(ComponentsUtility.java:63)
at org.sejda.common.ComponentsUtility.nullSafeCloseQuietly(ComponentsUtility.java:49)
at org.sejda.impl.sambox.MergeTask.closeResources(MergeTask.java:232)
at org.sejda.impl.sambox.MergeTask.after(MergeTask.java:237)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:151)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Thanks

**Comment by torakiki** [comment]
Please use the latest version 4 .deb we provide, it will work.
https://github.com/torakiki/pdfsam/releases
