### ISSUE TITLE
Merge error Java

### ISSUE THREAD

**Issue by jirilogr** [torakiki/pdfsam#314]
Merged pdf has 4300 sites and there is an error, I think there isn't about errors in PDF file:

INFO   [08:31:09]: Starting PDFsam
INFO   [08:31:11]: Configuring Sejda 3.2.56
INFO   [08:31:12]: Spuštěno v 3 seconds
INFO   [08:31:30]: To get higher rendering speed on JDK8 or later,
INFO   [08:31:30]:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
INFO   [08:31:30]:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")
INFO   [08:31:30]: B_Q-docum.for systems - komplet před výměnou.pdf loaded
INFO   [08:38:49]: B_Q-docum. for systems velký -- komplet-před výměnou.pdf loaded
INFO   [08:38:58]: Starting task (org.sejda.impl.sambox.SplitByPageNumbersTask@7f7ad9) execution.
ERROR  [08:39:00]: Unexpected error
java.lang.IllegalArgumentException: Cannot set position to a negative value
at org.sejda.util.RequireUtils.requireArg(RequireUtils.java:53)
at org.sejda.io.BufferedSeekableSource.position(BufferedSeekableSource.java:58)
at org.sejda.sambox.input.SourceReader.position(SourceReader.java:109)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.parseInUseEntry(LazyIndirectObjectsProvider.java:185)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.doParse(LazyIndirectObjectsProvider.java:174)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.parseObject(LazyIndirectObjectsProvider.java:133)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.parseCompressedEntry(LazyIndirectObjectsProvider.java:237)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.doParse(LazyIndirectObjectsProvider.java:178)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.parseObject(LazyIndirectObjectsProvider.java:133)
at org.sejda.sambox.input.LazyIndirectObjectsProvider.get(LazyIndirectObjectsProvider.java:75)
at org.sejda.sambox.input.ExistingIndirectCOSObject.getCOSObject(ExistingIndirectCOSObject.java:53)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Iterator.forEachRemaining(Unknown Source)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.LongPipeline.reduce(Unknown Source)
at java.util.stream.LongPipeline.sum(Unknown Source)
at java.util.stream.ReferencePipeline.count(Unknown Source)
at org.sejda.impl.sambox.component.optimization.OptimizationRuler.lambda$hasSharedFontDictionaries$15(OptimizationRuler.java:118)
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Iterator.forEachRemaining(Unknown Source)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.collect(Unknown Source)
at org.sejda.impl.sambox.component.optimization.OptimizationRuler.hasSharedFontDictionaries(OptimizationRuler.java:119)
at org.sejda.impl.sambox.component.optimization.OptimizationRuler.willNeedOptimization(OptimizationRuler.java:67)
at org.sejda.impl.sambox.component.optimization.OptimizationRuler.apply(OptimizationRuler.java:61)
at org.sejda.impl.sambox.SplitByPageNumbersTask.execute(SplitByPageNumbersTask.java:73)
at org.sejda.impl.sambox.SplitByPageNumbersTask.execute(SplitByPageNumbersTask.java:45)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:148)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by jirilogr** [comment]
Thanks, we found some errors in pdf file. After the fix of this error PDFSam merged this file without problems. JL
