### ISSUE TITLE
Errors on Linux Install

### ISSUE THREAD

**Issue by amandabee** [torakiki/pdfsam#346]
I installed using the Ubuntu Software Center in Ubuntu 18.04.2 LTS and had to specify Java8 via `sudo update-alternatives --config java` to get it to run at all (this was based on advice in the reviews). Now PDFsam launches, but if I try to merge two PDFs, I get an error: 

```
INFO   [14:36:32]: april04.pdf loaded
INFO   [14:36:32]: march21.pdf loaded
INFO   [14:36:36]: Starting task (org.sejda.impl.sambox.MergeTask@69730d7a) execution.
WARN   [14:36:37]: New fonts found, font cache will be re-built
WARN   [14:36:37]: Building on-disk font cache, this may take a while
ERROR  [14:36:37]: Unexpected error
java.lang.NoClassDefFoundError: Could not initialize class org.sejda.sambox.pdmodel.font.PDType1Font
at org.sejda.impl.sambox.util.FontUtils.<clinit>(FontUtils.java:74)
at org.sejda.impl.sambox.component.PDDocumentHandler.close(PDDocumentHandler.java:231)
at org.sejda.common.ComponentsUtility.nullSafeClose(ComponentsUtility.java:63)
at org.sejda.common.ComponentsUtility.nullSafeCloseQuietly(ComponentsUtility.java:49)
at org.sejda.impl.sambox.MergeTask.closeResources(MergeTask.java:232)
at org.sejda.impl.sambox.MergeTask.after(MergeTask.java:237)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:151)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

The two PDFs are "march21.pdf" and "april04.pdf" -- I'm able to merge them just fine with `pdftk` --  `pdftk march21.pdf april04.pdf cat output merged.pdf` 

I'm getting the same errors with any PDFs I try to merge.

**Comment by torakiki** [comment]
Yes, that's because of package that is in the repo and out of our hands. I'd suggest to uninstall PDFsam you installed from the repo, uninstall openjdk and openjfx (unless you need them for some other application), download the latest .deb we provide from [here](https://github.com/torakiki/pdfsam/releases/tag/v4.0.1) and that's it, it already contains the runtime and should work out of the box.
