### ISSUE TITLE
PDFSAM Basic 4.0.3: Error consistently reproducible w/ WORKAROUND

### ISSUE THREAD

**Issue by penalvch** [torakiki/pdfsam#363]
What happens is I am in 'Merge', I successfully Run and make a viewable PDF. I Clear, then Add, and get the below in Error Log.

WORKAROUND: Close and reopen PDFSAM Basic.

I can consistently reproduce problem with environment:
Windows 10 x64 1903 OS Build 18362.295
PDFSAM Basic 4.0.3

Error Log:

INFO   [10:57:49]: Starting PDFsam
INFO   [10:57:51]: Configuring Sejda 3.2.75
INFO   [10:57:51]: Workspace loaded
INFO   [10:57:51]: Started in 2 seconds
INFO   [10:57:59]: p13.pdf loaded
INFO   [10:57:59]: p14.pdf loaded
INFO   [10:57:59]: p15.pdf loaded
INFO   [10:57:59]: p16.pdf loaded
INFO   [10:57:59]: p17.pdf loaded
INFO   [10:58:01]: Starting task (org.sejda.impl.sambox.MergeTask@45da73fe) execution.
INFO   [10:58:01]: Task (org.sejda.impl.sambox.MergeTask@45da73fe) executed in 0 seconds
ERROR  [10:58:40]: Unexpected error
java.lang.IllegalArgumentException: Folder parameter must be a valid folder
at com.sun.glass.ui.CommonDialogs.convertFolder(CommonDialogs.java:239)
at com.sun.glass.ui.CommonDialogs.showFileChooser(CommonDialogs.java:191)
at com.sun.javafx.tk.quantum.QuantumToolkit.showFileChooser(QuantumToolkit.java:1557)
at javafx.stage.FileChooser.showDialog(FileChooser.java:413)
at javafx.stage.FileChooser.showOpenMultipleDialog(FileChooser.java:370)
at org.pdfsam.ui.io.RememberingLatestFileChooserWrapper.showOpenMultipleDialog(RememberingLatestFileChooserWrapper.java:58)
at org.pdfsam.ui.selection.multiple.SelectionTableToolbar$AddButton.loadDocuments(SelectionTableToolbar.java:105)
at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
at javafx.event.Event.fireEvent(Event.java:198)
at javafx.scene.Node.fireEvent(Node.java:8890)
at javafx.scene.control.SplitMenuButton.fire(SplitMenuButton.java:107)
at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
at com.sun.javafx.scene.control.behavior.MenuButtonBehaviorBase.mouseReleased(MenuButtonBehaviorBase.java:164)
at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$1(MenuButtonSkinBase.java:103)
at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)

**Comment by torakiki** [comment]
closed by https://github.com/torakiki/pdfsam/commit/608bbe6cee72b87e11fad6e331bddde9a22429f8
