### ISSUE TITLE
Issue on Windoes 10 with very long paths

### ISSUE THREAD

**Issue by torakiki** [torakiki/pdfsam#378]
See https://bugs.openjdk.java.net/browse/JDK-8165748 and https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path 
````
ERROR 14:39:50.821 org.pdfsam.UncaughtExceptionLogger[JavaFX Application Thread] Unexpected error
java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\E:\delete\sssssssssssssssssssssssssssssssssssssssssssssssss\PDFsam_merge.pdf
        at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.sejda.conversion.FileOutputAdapter.<init>(FileOutputAdapter.java:37)
        at org.pdfsam.ui.io.BrowsablePdfOutputField.apply(BrowsablePdfOutputField.java:50)
        at org.pdfsam.merge.MergeModule.getBuilder(MergeModule.java:111)
        at org.pdfsam.merge.MergeModule.getBuilder(MergeModule.java:61)
````

Windows OS and an old Java bug nobody cares, gimme mooore! Luckily it's 2019 and we can submit PR... oh wait, no we can't

**Comment by torakiki** [comment]
I tried to fix it by using the old `File` but ended up with:
```
ERROR 16:04:49.094 org.pdfsam.UncaughtExceptionLogger[pool-3-thread-1] Unexpected error
java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\E:\delete\sssssssssssssssssssssssssssssssssssssssssssssssss
        at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.io.File.toPath(File.java:2290)
        at java.base/java.io.WinNTFileSystem.getNameMax(WinNTFileSystem.java:639)
        at java.base/java.io.File$TempDirectory.generateFile(File.java:1939)
        at java.base/java.io.File.createTempFile(File.java:2076)
        at org.sejda.core.support.io.IOUtils.createTemporaryBuffer(IOUtils.java:108)
```
I guess there isn't anything we can do until they fix the `Path`
