### ISSUE TITLE
Alternate Mix crash

### ISSUE THREAD

**Issue by MrMoxy** [torakiki/pdfsam#401]
Using the Alternate Mix function causes a Java related crash.

PDF Split and Merge Basic Edition
4.1.3
OpenJDK Runtime Environment 11.0.7+10
Vendor: AdoptOpenJDK
Java runtime path: C:\Program Files (x86)\PDFsam Basic\runtime
JavaFX runtime version 14.0.1+1
Max memory 512 MB

Log as follows...
INFO   [16:32:53]: Starting PDFsam
INFO   [16:32:54]: Configuring Sejda 4.0.8
INFO   [16:32:55]: Started in 1 second
INFO   [16:44:29]: TestScanOdd.PDF loaded
INFO   [16:44:35]: TestScanEven.PDF loaded
INFO   [16:44:53]: Starting task (org.sejda.impl.sambox.AlternateMixTask@51f01b3c) execution.
ERROR  [16:44:53]: Unexpected error
java.lang.NullPointerException: null
at java.base/java.nio.file.Files.provider(Unknown Source)
at java.base/java.nio.file.Files.exists(Unknown Source)
at org.sejda.core.support.io.IOUtils$TmpBufferLocationFinder.dispatch(IOUtils.java:217)
at org.sejda.model.output.FileTaskOutput.accept(FileTaskOutput.java:62)
at org.sejda.core.support.io.IOUtils.createTemporaryBuffer(IOUtils.java:74)
at org.sejda.impl.sambox.AlternateMixTask.execute(AlternateMixTask.java:64)
at org.sejda.impl.sambox.AlternateMixTask.execute(AlternateMixTask.java:41)
at org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:141)
at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:64)
at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

All other program functions (eg. Split) work fine on the PDFs.

Tried a reinstall to no effect.

**Comment by torakiki** [comment]
This has been fixed here https://github.com/torakiki/sejda/commit/0cfb49498f1fbb67891f68e177890d4507c3d0dd and will be included in the next release. 
Try specifying the full path for the output file, that should fix the issue.
