### ISSUE TITLE
Exception when splitting 

### ISSUE THREAD

**Issue by elboukhari** [torakiki/pdfsam#410]
Exception under Ubuntu : 

`:~$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
:~$ 
` 
OS : 
`Linux linux 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

And here is the stacktrace : 

`ERROR 12:34:23.615 org.pdfsam.UncaughtExceptionLogger[pool-2-thread-1] Unexpected error
java.lang.NoClassDefFoundError: javax/validation/ParameterNameProvider
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:33)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:173)
	at org.sejda.core.validation.DefaultValidationContext.<init>(DefaultValidationContext.java:41)
	at org.sejda.core.validation.DefaultValidationContext.<init>(DefaultValidationContext.java:36)
	at org.sejda.core.validation.DefaultValidationContext$DefaultValidationContextHolder.<clinit>(DefaultValidationContext.java:70)
	at org.sejda.core.validation.DefaultValidationContext.getContext(DefaultValidationContext.java:50)
	at org.sejda.core.service.DefaultTaskExecutionService.validate(DefaultTaskExecutionService.java:104)
	at org.sejda.core.service.DefaultTaskExecutionService.validateIfRequired(DefaultTaskExecutionService.java:97)
	at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:66)
	at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
	at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.validation.ParameterNameProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 common frames omitted
INFO  12:35:09.649 o.p.PdfsamApp[JavaFX Application Thread] Fermeture de PDFsam...
Exception in Application stop method
ERROR 12:35:09.698 org.pdfsam.UncaughtExceptionLogger[main] Unexpected error
java.lang.RuntimeException: Exception in Application stop method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:905)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.sejda.eventstudio.exception.EventStudioException: Reflective method invocation exception
	at org.sejda.eventstudio.Listeners$ReflectiveListenerWrapper.onEvent(Listeners.java:251)
	at org.sejda.eventstudio.Station.doBroadcast(Station.java:94)
	at org.sejda.eventstudio.Station.broadcast(Station.java:80)
	at org.sejda.eventstudio.DefaultEventStudio.broadcast(DefaultEventStudio.java:208)
	at org.pdfsam.PdfsamApp.stop(PdfsamApp.java:227)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$10(LauncherImpl.java:865)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sejda.eventstudio.Listeners$ReflectiveListenerWrapper.onEvent(Listeners.java:244)
	... 13 common frames omitted
Caused by: java.lang.StackOverflowError: null
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._verifyValueWrite(WriterBasedJsonGenerator.java:891)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeStartObject(WriterBasedJsonGenerator.java:296)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter.writeBeanValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.BeanWriter.writeValue(BeanWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter._writeValue(JSONWriter.java)
`

And here is the conf as detected by PDFSam : 
`PDF Split and Merge Basic Edition
4.0.4
OpenJDK Runtime Environment 11.0.7+10-post-Ubuntu-3ubuntu1
Vendor: Ubuntu
chemin d'accès à Java runtime : /usr/lib/jvm/java-11-openjdk-amd64
JavaFX runtime version 11.0.6-internal+0-2020-04-14-123056
Mémoire maxi. 512 MB`

**Comment by torakiki** [comment]
I think this is an issue with the official Debian package. We provide our .deb archive you can get from https://pdfsam.org/download-pdfsam-basic/ and it will work. There is an issue already opened in the official Debian repos  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942507 but we don't maintain that.
