### ISSUE TITLE
Exception when merging files

### ISSUE THREAD

**Issue by erotavlasme** [torakiki/pdfsam#420]
Hi,
when I try to merge two or more files, I got the following error:
```
ERROR 08:52:33.350 org.pdfsam.UncaughtExceptionLogger[pool-3-thread-1] Unexpected error
java.lang.NoClassDefFoundError: javax/validation/ParameterNameProvider
	at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:33)
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:173)
	at org.sejda.core.validation.DefaultValidationContext.<init>(DefaultValidationContext.java:41)
	at org.sejda.core.validation.DefaultValidationContext.<init>(DefaultValidationContext.java:36)
	at org.sejda.core.validation.DefaultValidationContext$DefaultValidationContextHolder.<clinit>(DefaultValidationContext.java:70)
	at org.sejda.core.validation.DefaultValidationContext.getContext(DefaultValidationContext.java:50)
	at org.sejda.core.service.DefaultTaskExecutionService.validate(DefaultTaskExecutionService.java:104)
	at org.sejda.core.service.DefaultTaskExecutionService.validateIfRequired(DefaultTaskExecutionService.java:97)
	at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:66)
	at org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:58)
	at org.pdfsam.task.TaskExecutionController.lambda$request$0(TaskExecutionController.java:87)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.validation.ParameterNameProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 common frames omitted
```

```
PDF Split and Merge Basic Edition
4.0.4
OpenJDK Runtime Environment 11.0.8+10-post-Ubuntu-0ubuntu120.04
Vendor: Ubuntu
Java runtime path: /usr/lib/jvm/java-11-openjdk-amd64
JavaFX runtime version 11.0.6-internal+0-2020-04-14-123056
Max memory 512 MB
```
P.S. I tried with java 8, but I get this error:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/pdfsam/basic/App has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by erotavlasme** [comment]
I found that the latest version 4.1.4 available from pdfsam web site works well. So it is a question of package update, could you do it?

**Comment by torakiki** [comment]
No sorry, we are not the ones maintaining the Debian package. This is the Debian repo https://salsa.debian.org/java-team/pdfsam and this is an issue already open that I think is the same as the one you reported https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942507
I can try to help if they get in touch and they need some help.. from what I can tell at first sight there is a wrong version of Hibernate Validator as dependency

**Comment by erotavlasme** [comment]
I think that the best way on ubuntu is to update the package while on debian is to resolve the issue. Can you reach them?
