### ISSUE TITLE
StackOverflowError with jackson-jr 2.11.1

### ISSUE THREAD

**Issue by apoleon** [torakiki/pdfsam#431]
Hi,

In Debian we have upgraded jackson-jr to version 2.11.1 together with other jackson-* libraries. PDFsam still depends on version 2.9.10. With 2.11.1 I observe a StackOverflowError when I quit PDFsam. Any idea what could be the root cause for this problem? This is Debian bug 973125. The exception looks like this:

Exception in Application stop method
ERROR 18:33:20.952 org.pdfsam.UncaughtExceptionLogger[main] Unexpected error
java.lang.RuntimeException: Exception in Application stop method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:905)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.pdfsam.eventstudio.exception.EventStudioException: Reflective method invocation exception
	at org.pdfsam.eventstudio.Listeners$ReflectiveListenerWrapper.onEvent(Listeners.java:251)
	at org.pdfsam.eventstudio.Station.doBroadcast(Station.java:94)
	at org.pdfsam.eventstudio.Station.broadcast(Station.java:80)
	at org.pdfsam.eventstudio.DefaultEventStudio.broadcast(DefaultEventStudio.java:208)
	at org.pdfsam.PdfsamApp.stop(PdfsamApp.java:227)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$10(LauncherImpl.java:865)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.pdfsam.eventstudio.Listeners$ReflectiveListenerWrapper.onEvent(Listeners.java:244)
	... 13 common frames omitted
Caused by: java.lang.StackOverflowError: null
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeStartObject(WriterBasedJsonGenerator.java:296)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter.writeBeanValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.BeanWriter.writeValue(BeanWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter._writeValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter.writeBeanValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.BeanWriter.writeValue(BeanWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter._writeValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter.writeBeanValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.BeanWriter.writeValue(BeanWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter._writeValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter.writeBeanValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.BeanWriter.writeValue(BeanWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter._writeValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.JSONWriter.writeBeanValue(JSONWriter.java)
	at com.fasterxml.jackson.jr.ob.impl.BeanWriter.writeValue(BeanWriter.java)

**Comment by torakiki** [comment]
Looks like they changed default value for a Feature in Jackson jr https://github.com/FasterXML/jackson-jr/commit/5b7e783ce548a198351ca73621e60c6a331c81d9
