### ISSUE TITLE
Merge Failed: See error code below

### ISSUE THREAD

**Issue by InfinitWail** [torakiki/pdfsam#556]
Caused by: java.nio.file.NoSuchFileException: C:\Users

When browsing for folder to save in it fails to select and says "file not found".

**Comment by InfinitWail** [comment]
at org.sejda.model@5.0.6/org.sejda.model.output.FileTaskOutput.accept(FileTaskOutput.java:64)
at org.sejda.impl.sambox@5.0.6/org.sejda.impl.sambox.MergeTask.execute(MergeTask.java:257)
at org.sejda.impl.sambox@5.0.6/org.sejda.impl.sambox.MergeTask.execute(MergeTask.java:74)
at org.sejda.core@5.0.6/org.sejda.core.service.DefaultTaskExecutionService.actualExecution(DefaultTaskExecutionService.java:148)
at org.sejda.core@5.0.6/org.sejda.core.service.DefaultTaskExecutionService.execute(DefaultTaskExecutionService.java:71)
at org.pdfsam.service@5.1.3/org.pdfsam.service.task.TaskExecutionController.lambda$request$2(TaskExecutionController.java:88)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.NoSuchFileException: C:\Users\sandr\AppData\Local\Temp\pdfsam4319960566410724121.tmp -> F:\file1\file2\2023\07-2023\fuel\38\PDFsam_merge.pdf
at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
at java.base/java.nio.file.Files.copy(Unknown Source)
at org.apache.commons.io@2.11.0/org.apache.commons.io.FileUtils.copyFile(FileUtils.java:850)
at org.apache.commons.io@2.11.0/org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2308)
at org.apache.commons.io@2.11.0/org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2283)
at org.sejda.core@5.0.6/org.sejda.core.support.io.OutputWriterHelper.doMoveFile(OutputWriterHelper.java:167)
at org.sejda.core@5.0.6/org.sejda.core.support.io.OutputWriterHelper.moveFile(OutputWriterHelper.java:160)
at org.sejda.core@5.0.6/org.sejda.core.support.io.DefaultSingleOutputWriter.dispatch(DefaultSingleOutputWriter.java:72)
at org.sejda.model@5.0.6/org.sejda.model.output.FileTaskOutput.accept(FileTaskOutput.java:62)
... 8 more

**Comment by torakiki** [comment]
Does this happen consistently, every time you run the task? Does it work if you set the output on the C: drive?

**Comment by InfinitWail** [comment]
Just checked the C: drive and it worked, so must be F: that has problems?

**Comment by torakiki** [comment]
I don't think it's something in our code since it's Java nio throwing the exception. Few things you can check:

- File permissions on the F: drive
- F: drive is still available
- An antivirus is interfering
